import "./globals.css";
import ThemeRegistry from "./component/ThemeRegistry";

export const metadata = {
  title: "Video Menu",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeRegistry>
        <body>{ children }</body>
      </ThemeRegistry>

    </html>
  );
}
