import './globals.css';
import { Inter } from 'next/font/google';
import Nav from './{components}/Nav';
//== fortawesome
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
config.autoAddCss = false;//== prevent auto-injection of CSS

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ inter.className }>
        <div className='flex flex-col h-screen max-h-screen'>
          <Nav />
          <div className='flex-grow overflow-y-auto bg-amber-50'>
            { children }
          </div>
        </div>
      </body>
    </html>
  );
}
